name: Build YTLocalQueue

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: theos/setup-theos-action@v1
        with:
          arch: arm64 arm64e

      - name: Fetch YouTube Headers
        run: |
          git clone --depth=1 https://github.com/PoomSmart/YouTubeHeader.git Headers/YouTubeHeader
          git clone --depth=1 https://github.com/PoomSmart/PSHeader.git Headers/PSHeader

      - name: Build Tweak
        run: |
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1

      - name: Upload Compiled Package
        uses: actions/upload-artifact@v4
        with:
          name: YTLocalQueue-Build
          path: packages/*.deb
